Repository My-Epitech-Organisation/Jetpack, pull requests merged in 2025-04, with the labels that each got.

#3 Client integration
  .clang-format
  .gitignore
  Makefile
  client/CMakeLists.txt
  client/debug/debug.cpp
  client/debug/debug.hpp
  client/gamestate.cpp
  client/gamestate.hpp
  client/graphics/graphics.cpp
  client/graphics/graphics.hpp
  client/main.cpp
  client/network/network.cpp
  client/network/network.hpp
  client/network/protocol_handlers.cpp
  client/network/protocol_handlers.hpp
  client/protocol.hpp
  doc.txt
  server/check_args.c
  server/error_handling.c
  server/handle_client.c
  server/main.c
  server/parsing.c
  server/put_str_fd.c
  server/read_client.c
  server/send_game_messages.c
  server/send_messages_to_clients.c
  server/server.c
  server/set_server.c
Labels: documentation, enhancement

#7 Client integration
  Makefile
  client/debug/debug.cpp
  client/debug/debug.hpp
  client/graphics/graphics.cpp
  client/main.cpp
  client/network/network.cpp
  client/network/network.hpp
  client/network/protocol_handlers.cpp
  client/network/protocol_handlers.hpp
  client/protocol.hpp
  server/game_loop.c
  server/handle_client.c
  server/send_game_messages.c
Labels: enhancement

#9 Debug for the server part
  server/CMakeLists.txt
  server/error_handling.c
  server/game_loop.c
  server/get_types.c
  server/handle_client.c
  server/handle_input_from_clients.c
  server/includes/server.h
  server/parsing.c
  server/print_debug.c
  server/put_str_fd.c
  server/read_client.c
  server/send_game_messages.c
  server/send_messages_to_clients.c
  server/server.c
Labels: enhancement

#10 Client integration
  client/gamestate.cpp
  client/gamestate.hpp
  client/graphics/graphics.cpp
  client/network/network.cpp
  client/protocol.hpp
Labels: documentation, enhancement

#11 Handle input
  client/graphics/graphics.cpp
  doc.txt
  server/error_handling.c
  server/game_loop.c
  server/handle_client.c
  server/handle_input_from_clients.c
  server/includes/server.h
  server/load_map.c
  server/read_client.c
  server/send_game_messages.c
  server/send_messages_to_clients.c
  server/server.c
  server/set_server.c
Labels: enhancement

#12 [FIX](server): Update client position limits to match new map dimensions
  server/game_loop.c
Labels: enhancement

#13 Client integration
  client/CMakeLists.txt
  client/debug/debug.hpp
  client/gamestate.cpp
  client/gamestate.hpp
  client/graphics/graphics.cpp
  client/graphics/graphics.hpp
  client/graphics/input_handler.cpp
  client/graphics/input_handler.hpp
  client/graphics/renderer.cpp
  client/graphics/renderer.hpp
  client/main.cpp
  client/network/network.cpp
  client/network/network.hpp
  client/network/protocol_handlers.cpp
  client/protocol.hpp
  server/server.c
Labels: bug, enhancement

#14 Debug server
  server/includes/server.h
  server/print_debug.c
  server/read_client.c
  server/send_game_messages.c
  server/send_messages_to_clients.c
Labels: bug, enhancement

#15 Handle collisions
  client/gamestate.cpp
  client/gamestate.hpp
  client/graphics/graphics.cpp
  client/graphics/graphics.hpp
  client/graphics/renderer.cpp
  client/graphics/renderer.hpp
  client/main.cpp
  client/network/protocol_handlers.cpp
  client/protocol.hpp
  doc.txt
  server/CMakeLists.txt
  server/check_in_game.c
  server/game_loop.c
  server/includes/server.h
  server/read_client.c
  server/send_function.c
  server/send_game_messages.c
  server/server.c
  server/write_messages.c
Labels: enhancement

#16 [FIX](server): Update check_read function signature and logic; implem…
  server/error_handling.c
  server/includes/server.h
  server/read_client.c
  server/set_server.c
Labels: enhancement

#17 Client integration
  client/network/network.cpp
  client/network/network.hpp
  client/protocol.hpp
  doc.txt
Labels: documentation, enhancement

#18 [STYLE](client): Clean up comments and improve code readability acros…
  client/gamestate.cpp
  client/graphics/graphics.cpp
  client/graphics/input_handler.cpp
  client/graphics/renderer.cpp
  client/graphics/renderer.hpp
  client/main.cpp
  client/network/network.cpp
  client/network/protocol_handlers.cpp
  client/protocol.hpp
Labels: enhancement

#20 [FIX](server): Correct jetpack position calculation and update debug …
  server/check_in_game.c
  server/main.c
  server/print_debug.c
  server/send_game_messages.c
  server/server.c
Labels: bug, enhancement
